# Decision Graph Configuration for Microsoft Sample

[site]
title = "Microsoft Decision Archive"
description = "Key strategic decisions in Microsoft's history (1975-2014)"
primary_color = "#00A4EF"  # Microsoft Blue
accent_color = "#7FBA00"   # Microsoft Green
footer = "Microsoft Corporation (Sample)"
quick_preview = true

# Author profiles
[authors.billg]
name = "Bill Gates"
email = "billg@microsoft.com"
avatar_url = "https://pbs.twimg.com/profile_images/1674815862879178752/nTGMV1Eo_400x400.jpg"

[authors.steveb]
name = "Steve Ballmer"
email = "steveb@microsoft.com"
avatar_url = "https://pbs.twimg.com/profile_images/1255577663261773825/25t0tWj9_400x400.jpg"

[authors.paul]
name = "Paul Allen"
email = "paul@microsoft.com"

[authors.satya]
name = "Satya Nadella"
email = "satyan@microsoft.com"
avatar_url = "https://pbs.twimg.com/profile_images/1221837516816306177/_Ld4un5A_400x400.jpg"

[authors.cutler]
name = "Dave Cutler"
email = "davec@microsoft.com"

[authors.simonyi]
name = "Charles Simonyi"
email = "charles@microsoft.com"

[authors.sinofsky]
name = "Steven Sinofsky"
email = "stevesi@microsoft.com"

[authors.allard]
name = "Jay Allard"
email = "jallard@microsoft.com"

[authors.bradsmith]
name = "Brad Smith"
email = "bsmith@microsoft.com"

[authors.rayozzie]
name = "Ray Ozzie"
email = "rayozzie@microsoft.com"

[authors.myhrvold]
name = "Nathan Myhrvold"
email = "nathanm@microsoft.com"

[authors.maples]
name = "Mike Maples"
email = "mikem@microsoft.com"

[authors.ibm]
name = "IBM Project Chess Team"
email = "chess@ibm.com"

[authors.board]
name = "Microsoft Board"
email = "board@microsoft.com"

[authors.legal]
name = "Microsoft Legal"
email = "legal@microsoft.com"
